add sato_2006_effect_725
echemdb/website pull request #22
Opened 2021-10-11 13:00 UTC by linuxrider

2021-10-25 09:19 UTC, saraedum submitted a review, later dismissed

2022-01-24 13:21 UTC, linuxrider commented
Due to the unit in the scan rate text this depends on #svgdigitizer/#126.

2022-06-22 14:38 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725.bib
> +  title = {Effect of Sulfuric Acid Concentration on the Structure of Sulfate Adlayer on {{Au}}(1~1~1) Electrode},
```suggestion
  title = {Effect of Sulfuric Acid Concentration on the Structure of Sulfate Adlayer on Au(111) Electrode},
```

2022-06-22 14:38 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +        sum formula: H2SO4
```suggestion
      - name: H2SO4
```

2022-06-22 14:39 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +          LOT: null
```suggestion
```

2022-06-22 14:39 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +          LOT: null
All entries that are empty or contain `null`, `none` etc should be removed

2022-06-22 14:41 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +      estimated value (CurTiPot): 0.1
I think this should always be `value`.
Additional information could be stored in a key called `comment'.

2022-06-22 14:41 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +        value: null
```suggestion
```

2022-06-22 14:42 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +      preparation procedure: annealed in hydrogen flame (1 min) and subsequently quenched in ultrapure water
```suggestion
      preparation procedure: Annealed in hydrogen flame for 1 min and subsequently quenched in ultrapure water.
```

2022-06-22 14:45 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +
```suggestion
  - role: curator
    name: Johannes M. Hermann
    orcid: https://orcid.org/0000-0001-7119-1295
    date: 2021-10-11
  - role: reviewer
     name: Albert Engstfeld
     orcid: https://orcid.org/0000-0002-9686-3948
     date: 2022-06-22
```

2022-06-22 14:47 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +        sum formula: H2O
```suggestion
      - name: H2O
```

2022-06-22 14:49 UTC, DunklesArchipel requested changes
I made some changes to the YAML which would need to be adopted in the other files.
Also, I left you a personal note regarding the digitized curves to make them more smooth.

2022-06-22 19:20 UTC, linuxrider commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +      estimated value (CurTiPot): 0.1
@DunklesArchipel Do you agree with this approach?

2022-06-22 19:20 UTC, linuxrider commented
I think now all suggestions are applied.

2022-06-22 19:49 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +      estimated value (CurTiPot): 0.1
sure.

We should consider it in our metadata-schema. (see https://github.com/echemdb/metadata-schema/issues/22)

2022-06-22 19:50 UTC, DunklesArchipel commented on literature/sato_2006_effect_725/sato_2006_effect_725_p3_f4a_red.yaml
> +
```suggestion
```

2022-06-22 20:00 UTC, DunklesArchipel approved these changes
Looks good. I removed some empty lines and the instrumentation section, since it did not contain any meaningful information.

2022-06-22 20:02 UTC, DunklesArchipel commented
@saraedum there are some outdated change requests, which block the merging process. Could you please approve?

2022-06-23 05:10 UTC, merged

2022-06-23 05:14 UTC, linuxrider commented
@saraedum I used the option to dismiss your review of the outdated changes. Hope this is ok for you?
In general, is this bad practice to dismiss a review or is ok under such circumstances?