pajkossy_1996_impedance_209
echemdb/website pull request #57
Opened 2021-11-22 17:46 UTC by markus-chem

add lit folder

2021-11-23 20:04 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p2_1A_dotted.yaml
> +            crystallographic orientation: 111 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '111' # hkl, 100, 110, poly

```

2021-11-23 20:04 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p2_1A_solid.yaml
> +            crystallographic orientation: 111 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '111' # hkl, 100, 110, poly

```

2021-11-23 20:05 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p2_1B_dotted.yaml
> +            crystallographic orientation: 100 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '100' # hkl, 100, 110, poly

```

2021-11-23 20:05 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p2_1B_solid.yaml
> +            crystallographic orientation: 100 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '100' # hkl, 100, 110, poly

```

2021-11-23 20:05 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p3_3A_a.yaml
> +            crystallographic orientation: 111 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '111' # hkl, 100, 110, poly

```

2021-11-23 20:06 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p3_3A_b.yaml
> +            crystallographic orientation: 111 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '111' # hkl, 100, 110, poly

```

2021-11-23 20:07 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p3_3A_dashed.yaml
> +            crystallographic orientation: 111 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '111' # hkl, 100, 110, poly

```

2021-11-23 20:07 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p6_8A_a.yaml
> +            crystallographic orientation: 100 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '100' # hkl, 100, 110, poly

```

2021-11-23 20:07 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p6_8A_b.yaml
> +            crystallographic orientation: 100 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '100' # hkl, 100, 110, poly

```

2021-11-23 20:07 UTC, DunklesArchipel commented on literature/pajkossy_1996_impedance_209/pajkossy_1996_impedance_209_p6_8A_dashed.yaml
> +            crystallographic orientation: 100 # hkl, 100, 110, poly
```suggestion
            crystallographic orientation: '100' # hkl, 100, 110, poly

```

2021-11-23 20:08 UTC, DunklesArchipel requested changes
The crystallographic orientation was missing some ' '.
I Hopefully added all of them. Please check carefully.

2021-11-28 21:06 UTC, markus-chem commented
All hkl changed to string.

2021-11-30 09:04 UTC, markus-chem commented
> The crystallographic orientation was missing some ' '. I Hopefully added all of them. Please check carefully.

Done and checked.

2021-12-01 19:13 UTC, DunklesArchipel approved these changes
seems fine

2021-12-01 19:26 UTC, merged