Refactoring unit implementation for use in dataframes and plots
echemdb/website pull request #88
Opened 2021-12-03 11:39 UTC by DunklesArchipel

The data frames in the database do not contain any information on the currently used units. We create the data frame from the CSV file, which has been created with SI units.

In our previous version, the data frame could be created with units different from SI. However, the returned `df` obviously does not contain this information.

Such information is crucial for the plot module, where the units should be printed on the x and y-axis labels.

Another issue is that the y axis can be either a current (I) or a current density (j) with distinctly different units.

x and y units are now returned by `xy_units()`. It is possible to return SI units, custom units or the original units from the figure. 

Maybe there is a smarter quick and dirty solution than this one. Otherwise, we could wait for pandas 2.0 where unit storage along with data frames is eventually implemented.

Also the rendering of the Figure on the cv_entry.md has been updated. (Not yet super nice, but better than before.)

2021-12-04 23:56 UTC, saraedum commented
Do you have a link for that pandas update? I also would not mind to use an experimental change in pandas here.

2021-12-05 05:33 UTC, saraedum commented
> Do you have a link for that pandas update? I also would not mind to use an experimental change in pandas here.

I could not find any actual pandas 2 implementation. It seems to be just a rough roadmap.

2021-12-05 05:37 UTC, saraedum commented
Have you had a look at astropy time series? They support quantities, see https://docs.astropy.org/en/stable/timeseries/pandas.html.

2021-12-05 05:46 UTC, saraedum commented on echemdb/data/cv/entry.py
>          Return a plot of the database in this data package.
```suggestion
        Return a plot of the data in this data package.
```

2021-12-05 06:28 UTC, saraedum requested changes
I proposed a way to get rid of the I/j hack. Otherwise, this looks great apart from some wording issues, e.g., I am pretty sure that the lines in docstrings that end in `::` should not end in a `.`.

2021-12-05 06:28 UTC, saraedum commented on echemdb/data/cv/entry.py
> +        with the original figure units or with custom units as shown in the following examples.
```suggestion
        If the x and y-units are not specified, all values
        are in SI units. The data frame can also be returned 
        with the original figure units or with custom units as shown in the following examples.
```

No need to be super-precise here as it becomes clear from the examples for those that doubt.

2021-12-05 06:28 UTC, saraedum commented on echemdb/data/cv/entry.py
> +        The first example provides a data frame in SI units.::
```suggestion
        A data frame in SI units::
```

I would not number things because it makes inserting another example later painful.

2021-12-05 06:28 UTC, saraedum commented on echemdb/data/cv/entry.py
> +        The second example provides a dataframe in the original units of the figure.::
```suggestion
        A data frame in the original units of the figure::
```

2021-12-05 06:28 UTC, saraedum commented on echemdb/data/cv/entry.py
> +        The third example provides a dataframe with custom units.::
```suggestion
        A data frame with custom units::
```

2021-12-05 06:28 UTC, saraedum commented on echemdb/data/cv/entry.py
> +    def xy_units(self, xunit=None, yunit=None):
Why don't split this into `x_unit` and `y_unit`? There seems to be no interaction between the two parts of this method.

2021-12-05 06:28 UTC, saraedum commented on echemdb/data/cv/entry.py
> +                yunit = u.A
This if-j-if-I is really annoying.

Could we do the following: We have `x_unit` and `y_unit` which return the units of the axes, as you planned here. Then we have `x` and `y` which return the name of the axes, i.e., `U` and `I`/`j`.

```suggestion
            if self.y == 'j':
                yunit = u.A / u.m**2
            elif self.y == 'I':
                yunit = u.A
            else:
                raise NotImplementedError("Unexpected naming of y axis.")
```

Also, we should always catch unexpected values as early as possible, as this makes debugging much easier when something goes wrong.

2021-12-05 06:28 UTC, saraedum commented on echemdb/data/cv/entry.py
> +                            yaxis_title=ylabel)
```suggestion
        fig.add_trace(plotly.graph_objects.Scatter(x=df[self.x], y=df[self.y], mode='lines'))

        fig.update_layout(template="simple_white", showlegend=False, autosize=True, width=600, height=400, 
                            margin=dict(l=70, r=70, b=70, t=70, pad=7),
                            xaxis_title=f"{self.x} [{xunit}]",
                            yaxis_title=f"{self.y} [{yunit}]")
```

2021-12-20 19:25 UTC, DunklesArchipel commented
@saraedum I hopefully implemented all your changes.

The doctests fail probably due to the latest update on svgdigitizer that you did. I cannot reproduce that particular doctest error locally, even with the version of the svgdigitizer.

2021-12-21 03:11 UTC, saraedum commented
> @saraedum I hopefully implemented all your changes.
> 
> The doctests fail probably due to the latest update on svgdigitizer that you did. I cannot reproduce that particular doctest error locally, even with the version of the svgdigitizer.

Yes, I think that's the problem described at https://github.com/echemdb/website/blob/main/environment.yml#L30.

2021-12-23 19:28 UTC, saraedum commented
There are merge conflicts @DunklesArchipel .

2021-12-24 12:44 UTC, linuxrider approved these changes
Looks good to me.

2022-01-03 17:12 UTC, saraedum approved these changes
Looks great. I have just some minor comments. Feel free to merge once addressed.

2022-01-03 17:12 UTC, saraedum commented on echemdb/data/cv/entry.py
> +        return yunit
```suggestion
```suggestion
        return u.Unit(yunit)
```

`yunit` can already be a unit. `isinstance` is usually frowned upon in Python as it does not allow duck typing.

2022-01-03 17:12 UTC, saraedum commented on echemdb/data/cv/entry.py
> +        return xunit
```suggestion

        return u.Unit(xunit)
```

xunit can already be a unit. isinstance is usually frowned upon in Python as it does not allow duck typing.

2022-01-07 10:13 UTC, DunklesArchipel commented on echemdb/data/cv/entry.py
> +        r"""Return the x-axis name.
sounds good.

2022-01-07 10:15 UTC, DunklesArchipel commented on echemdb/data/cv/entry.py
> +            return 'U'
yes makes sense

2022-01-07 10:17 UTC, DunklesArchipel commented on echemdb/data/cv/entry.py
> +        r"""Return an astropy unit, where `xunit` is a voltage.
sounds good.

2022-01-07 10:52 UTC, merged